services:
  app:
    build: .
    container_name: eventmanager
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
      - eventmanager_network

networks:
  eventmanager_network:
    external: true
